
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install PS3 SDK Toolchain
        run: |
          docker pull sstewartgallay/ps3dev:latest
          
      - name: Build with Docker
        run: |
          docker run --rm -v $(pwd):/src sstewartgallay/ps3dev:latest sh -c "cd /src && make"
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MC_Remote_SPRX
          path: ./*.sprx
