name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: bucanero/ps3dev:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: MC_Remote_SPRX
          path: ./*.sprx